name: "finalproj"

services:
  java:
    build:
      context: ./back
      dockerfile: ./tomcat.dockerfile
      args:
        war_file: GoldenBowl.war
    container_name: goldenBowl-back
    ports:
      - "9080:8080"
    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://host.docker.internal:1433;database=back2;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=P@ssw0rd

  vue1:
    build:
      context: ./front-cus
      dockerfile: ./nginx.dockerfile
      args:
        config_file: nginx.conf
        publish_dir: dist
    container_name: vue-cus
    depends_on:
      - java
    environment:
      - TZ=Asia/Taipei
    ports:
      - "80:80"
      - "443:443"
      - "6173:6173"

  vue2:
    build:
      context: ./front-store
      dockerfile: ./nginx.dockerfile
      args:
        config_file: nginx.conf
        publish_dir: dist
    container_name: vue-store
    depends_on:
      - java
    environment:
      - TZ=Asia/Taipei
    ports:
      - "8081:80"
      - "8443:443"
      - "7173:6173"

  vue3:
    build:
      context: ./front-admin
      dockerfile: ./nginx.dockerfile
      args:
        config_file: nginx.conf
        publish_dir: dist
    container_name: vue-admin
    depends_on:
      - java
    environment:
      - TZ=Asia/Taipei
    ports:
      - "8082:80"
      - "8444:443"
      - "9174:6173"