name: "finalproj"

services:
  java:
    build:
      context: ./back
      dockerfile: ./tomcat.dockerfile
      args:
        war_file: GoldenBowl.war
    container_name: goldenBowl-back
    ports:
      - "9080:8080"
    depends_on:
      - sqlserver
    # 這裡可以添加環境變數來讓 Java 連接到 SQL Server 服務名稱
    environment: # 取消註解並確認這些變數
      - DB_HOST=sqlserver # 使用 SQL Server 服務的名稱作為主機
      - DB_PORT=1433      # 使用 SQL Server 容器內部預設的埠號
      - DB_NAME=back2     # 您的資料庫名稱
      - DB_USER=sa        # 您的資料庫使用者名稱
      - DB_PASSWORD=P@ssw0rd # 您的資料庫密碼
  
  vue1:
    build:
      context: ./front-cus
      dockerfile: ./nginx.dockerfile
      args:
        config_file: nginx.conf
        publish_dir: dist
    container_name: vue-cus
    depends_on:
      - java
    environment:
      - TZ=Asia/Taipei
    ports:
      - "80:80"
      - "443:443"
      - "6173:6173"

  vue2:
    build:
      context: ./front-store
      dockerfile: ./nginx.dockerfile
      args:
        config_file: nginx.conf
        publish_dir: dist
    container_name: vue-store
    depends_on:
      - java
    environment:
      - TZ=Asia/Taipei
    ports:
      - "8081:80"
      - "8443:443"
      - "7173:6173"

  vue3:
    build:
      context: ./front-admin
      dockerfile: ./nginx.dockerfile
      args:
        config_file: nginx.conf
        publish_dir: dist
    container_name: vue-admin
    depends_on:
      - java
    environment:
      - TZ=Asia/Taipei
    ports:
      - "8082:80"
      - "8444:443"
      - "9174:6173"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-back
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
      - MSSQL_COLLATION=Chinese_Taiwan_Stroke_CI_AS
      - TZ=Asia/Taipei
    ports:
      - "9433:1433"
    volumes:
      - mssqlsystem:/var/opt/mssql
      - mssqluser:/var/opt/sqlserver

volumes:
  mssqlsystem:
  mssqluser:
