jwt:
  token:
    expire: 10

spring:
  application:
    name: GoldenBowl

  output:
    ansi:
      enabled: always

  #設定profile
  # profiles:
  #   active: "@xxx@"

  #設定資料庫執行環境
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # 將這裡的 url、username 和 password 改為使用環境變數
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};database=${DB_NAME};trustServerCertificate=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  # 設定JPA
  jpa:
    show-sql: true
    #顯示資料庫語法
    database-platform: org.hibernate.dialect.SQLServerDialect # 讓java語法轉為SQL語法
    hibernate:
      ddl-auto: update
      #update 更新java entity時，也會創建
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        #會自動捕捉entity讓你不用備註column
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #連結資料庫讓名稱與java相同
  #mogodb的設定
  #   data:
  #     mongodb:
  #       host: localhost
  #       port: 27017
  #       database: textdb

  #設定Jackson的日期轉換格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Taipei

  #設定google登入
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

app:
  frontend:
    url: http://localhost:5173
